"""1_user

Revision ID: 0238ee6479cd
Revises: 
Create Date: 2024-03-17 16:20:16.964884

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from app.contrib.account import GenderChoices

# revision identifiers, used by Alembic.
revision = '0238ee6479cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinecone_api_info',
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('env', sa.String(length=255), nullable=False),
                    sa.Column('key', sa.String(length=255), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('hashed_password', sa.String(length=255), nullable=False),
                    sa.Column('gender', sqlalchemy_utils.types.choice.ChoiceType(
                        choices=GenderChoices, impl=sa.String(25)
                    ), nullable=True),
                    sa.Column('birthday', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('signature', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('file_info',
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('file_name', sa.String(length=255), nullable=False),
                    sa.Column('file', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fx_file_info_user_id', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_info')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('pinecone_api_info')
    # ### end Alembic commands ###
