"""3_protocol

Revision ID: 1943935a1011
Revises: 394854b45131
Create Date: 2024-03-17 16:55:18.318260

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1943935a1011'
down_revision = '394854b45131'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'protocol',
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('step', sa.Integer(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_id'), 'protocol', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_protocol_id'), table_name='protocol')
    op.drop_table('protocol')
    # ### end Alembic commands ###
