"""3_protocol

Revision ID: 2fc8d85db0b6
Revises: 301acc0d2769
Create Date: 2024-04-13 17:41:30.183117

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from app.contrib.protocol import ProtocolSourceChoices, FileType

# revision identifiers, used by Alembic.
revision = '2fc8d85db0b6'
down_revision = '301acc0d2769'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'protocol',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('current_step', sa.String(), nullable=False),
        sa.Column('medicine', sa.String(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fx_protocol_user_id', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_id'), 'protocol', ['id'], unique=False)
    op.create_table(
        'protocol_file',
        sa.Column('protocol_id', sa.UUID(), nullable=False),
        sa.Column('file_type', sqlalchemy_utils.types.choice.ChoiceType(
            choices=FileType, impl=sa.String(25)
        ), nullable=False),
        sa.Column('file_path', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['protocol_id'], ['protocol.id'], name='fx_p_file_protocol_id',
                                ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('protocol_id', 'file_type', name='ux_protocol_id_file_type')
    )
    op.create_table(
        'protocol_step',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('protocol_id', sa.UUID(), nullable=False),
        sa.Column('question', sa.Text(), nullable=False),
        sa.Column('prompt', sa.Text(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('source', sqlalchemy_utils.types.choice.ChoiceType(
            choices=ProtocolSourceChoices, impl=sa.String(length=25)
        ), nullable=False),
        sa.Column('step', sa.String(length=50), nullable=False),
        sa.Column('step_order', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['protocol_id'], ['protocol.id'], name='fx_p_step_protocol_id',
                                ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fx_protocol_step_user_id',
                                ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('protocol_id', 'step', name='ux_protocol_id_step')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protocol_step')
    op.drop_table('protocol_file')
    op.drop_index(op.f('ix_protocol_id'), table_name='protocol')
    op.drop_table('protocol')
    # ### end Alembic commands ###
