"""7_email_verified_at

Revision ID: 473c2b722d39
Revises: c7b9164ea538
Create Date: 2024-04-09 17:45:12.415768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473c2b722d39'
down_revision = 'c7b9164ea538'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verified_at')
    # ### end Alembic commands ###
