"""6_protocol_file

Revision ID: c7b9164ea538
Revises: ca1e88951622
Create Date: 2024-03-31 17:33:05.252867

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from app.contrib.protocol import FileType

# revision identifiers, used by Alembic.
revision = 'c7b9164ea538'
down_revision = 'ca1e88951622'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'protocol_file',
        sa.Column('protocol_id', sa.UUID(), nullable=False),
        sa.Column('file_type', sqlalchemy_utils.types.choice.ChoiceType(
            choices=FileType, impl=sa.String(25)
        ), nullable=False),
        sa.Column('file_path', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['protocol_id'], ['protocol.id'], name='fx_p_file_protocol_id', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('protocol_id', 'file_type', name='ux_protocol_id_file_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protocol_file')
    # ### end Alembic commands ###
