"""5_protocol_current_step

Revision ID: ca1e88951622
Revises: 578d557928f3
Create Date: 2024-03-30 00:46:16.696592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1e88951622'
down_revision = '578d557928f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('protocol', 'current_step',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('protocol', 'current_step',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
